---
ID: "cdde915b-8683-4a77-b81d-0fd4a44e6733"
Parent: "57ef2947-e240-456e-bcaa-b0dae7b83d04"
Template: "57ef2947-e240-456e-bcaa-b0dae7b83d04"
Path: /sitecore/templates/Feature/DemoSite/Basic Content/RichText/RichTextFullRenderingParameters/__Standard Values
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
            Hint: __Created
            Value: 20230721T190000Z
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "de43adfb-d8ac-4f6e-a112-ff80e005829f"
          - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
            Hint: __Updated by
            Value: |
              sitecore\Admin
          - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
            Hint: __Updated
            Value: 20230721T190000Z
