---
ID: "fdcf7fb4-436c-4e79-a94a-07bad3bc651d"
Parent: "9ba7e460-4685-48bc-bf96-5c88a45fe261"
Template: "0437fee2-44c9-46a6-abe9-28858d9fee8c"
Path: /sitecore/templates/Foundation/DemoSite/Settings
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "01db0b63-75a1-49c4-80ef-67326943d67b"
