---
ID: "b37d477b-5237-4478-af3b-e675b993a60d"
Parent: "9946073e-f1f9-4fb9-9814-833d4ceabcb3"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/DemoSite/DemoSiteWebsite/Presentation/Headless Variants/Navigation/Default
BranchID: "70519928-c595-4b2b-bb35-75022feecc4c"
SharedFields:
  - ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
    Hint: __Originator
    Value: "{25F1A8E5-EB4C-4202-A9F7-A97DB52DA9AF}"
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "2b1f4f66-74eb-4756-aa18-e19953ea368e"
