---
ID: "3a7800f7-12be-4bb2-9c19-1ac475380a0e"
Parent: "61ff408b-5420-4146-a3e4-23683b8632bc"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/DemoSite/DemoSiteWebsite/Presentation/Headless Variants/Image/Default
BranchID: "ae87ba03-4197-4107-82d5-f8b1cafe3bff"
SharedFields:
  - ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
    Hint: __Originator
    Value: "{715BA68D-500D-4C0C-A611-8AD2B3478B21}"
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "2ecdeaa1-0872-428b-929f-df24205a9647"
