---
ID: "8e692893-a6b3-48b5-b351-c80129c5b7e9"
Parent: "4dd932c2-fe9b-494d-8853-b00afaf084e6"
Template: "4dd932c2-fe9b-494d-8853-b00afaf084e6"
Path: /sitecore/templates/Feature/DemoSite/Common/LinkWithLang/__Standard Values
SharedFields:
  - ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
    Hint: __Default workflow
    Value: "{33D3E219-6951-4F62-A015-183C3E1C4CF0}"
  - ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
    Hint: __Enable item fallback
    Value: 1
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "6fe446d5-2199-49d5-b6af-19bac5e2715a"
