---
ID: "a8bcfadc-e382-46f3-9cf6-e6da8f9ab6b5"
Parent: "4dfbfa34-b95c-434c-90e8-279c95a42587"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/DemoSite/DemoSiteWebsite/Presentation/Headless Variants/Promo/Default
BranchID: "37229eac-e94c-4507-b543-6cb1f31294e4"
SharedFields:
  - ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
    Hint: __Originator
    Value: "{C8F0AA39-7D5A-4BD2-9452-C21B3BFED25D}"
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "81691521-14d9-4607-bb36-4fed542b6f83"
