---
ID: "76f1e929-7ebb-4940-acb4-ee98c6ce8056"
Parent: "e29a8175-d3d3-4b00-949a-3b1e8ea15e45"
Template: "e29a8175-d3d3-4b00-949a-3b1e8ea15e45"
Path: /sitecore/templates/Feature/DemoSite/Navigation/Header/PrimaryNavigationSection/__Standard Values
SharedFields:
  - ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
    Hint: __Masters
    Value:
  - ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
    Hint: __Default workflow
    Value: "{33D3E219-6951-4F62-A015-183C3E1C4CF0}"
  - ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
    Hint: __Enable item fallback
    Value: 1
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "9893bc04-4994-43f4-a6a0-9a401b07cfb7"
          - ID: "b5f94aca-b64a-4aee-94af-8f9c8645d15e"
            Hint: title
            Value: $name
