---
ID: "31812475-94bd-4f07-9359-8ccd1fcadb89"
Parent: "8045f907-8294-4e77-bbcd-f4b37ae3d7ee"
Template: "8045f907-8294-4e77-bbcd-f4b37ae3d7ee"
Path: /sitecore/templates/Feature/DemoSite/Basic Content/Wistia Video Player/WistiaVideoFolder/__Standard Values
SharedFields:
  - ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
    Hint: __Masters
    Value: |
      {B0980196-CFEC-47D2-9A5C-8E157054D4B3}
      {8045F907-8294-4E77-BBCD-F4B37AE3D7EE}
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "6aa4f138-5061-4e1f-952e-13273603dffd"
