---
ID: "67915ed4-1812-5251-800b-425bbc7a77f0"
Parent: "c85eed0a-4306-558d-8169-6c49f7489cdd"
Template: "c85eed0a-4306-558d-8169-6c49f7489cdd"
Path: "/sitecore/templates/Project/DemoSite/Styleguide/Styleguide-FieldUsage-Date/__Standard Values"
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\JssImport
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "f0aa6949-3642-4c53-8942-cf142bb41981"
