---
ID: "af5bad1c-bcd9-5f82-ac4e-b8d1e4b39fe1"
Parent: "c598e2a7-165f-56da-bf5a-96ba78825c81"
Template: "c598e2a7-165f-56da-bf5a-96ba78825c81"
Path: "/sitecore/templates/Project/DemoSite/Styleguide/Styleguide-Multilingual/__Standard Values"
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\JssImport
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "f1107829-db3e-47c4-90c0-2f037e9d670c"
