---
ID: "20d0dfc4-bc72-4b55-ba99-8d6e672b1aed"
Parent: "fc1cef11-a4e0-4ba7-ba77-6eb2a610c6fd"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Foundation/DemoSite/Navigation/_NavigationSiteSettings
SharedFields:
  - ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
    Hint: __Base template
    Value: "{1930BBEB-7805-471A-A3BE-4858AC7CF696}"
  - ID: "f7d48a55-2158-4f02-9356-756654404f73"
    Hint: __Standard values
    Value: "{849DD05B-3E45-4712-8757-86A7ADDB3A8F}"
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
            Hint: __Created
            Value: 20230720T203237Z
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "bfa07746-7795-4f05-a516-6bb5120f221a"
          - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
            Hint: __Updated by
            Value: |
              sitecore\Admin
          - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
            Hint: __Updated
            Value: 20230720T203237Z
