---
ID: "974b9d42-2500-44cc-89c5-d0b05a329e42"
Parent: "6b724312-f46b-47a0-bbae-35ef47421103"
Template: "6b724312-f46b-47a0-bbae-35ef47421103"
Path: /sitecore/templates/Feature/DemoSite/Callouts/Stacked Icon Callout/Stacked Icon Callout/__Standard Values
SharedFields:
  - ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
    Hint: __Default workflow
    Value: "{33D3E219-6951-4F62-A015-183C3E1C4CF0}"
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
            Hint: __Created
            Value: 20230727T171628Z
          - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
            Hint: __Owner
            Value: |
              sitecore\Admin
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "e655d414-5549-4c5c-b295-335b6a8d2803"
          - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
            Hint: __Updated by
            Value: |
              sitecore\Admin
          - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
            Hint: __Updated
            Value: 20230727T172821Z
