---
ID: "6e190624-6175-4354-9dd0-109a579f300e"
Parent: "f21983d8-c426-4a3f-9307-c53fa3fb7dd1"
Template: "f21983d8-c426-4a3f-9307-c53fa3fb7dd1"
Path: /sitecore/templates/Feature/DemoSite/Banners/Page Banner With Overlay/PageBannerWithOverlayFolder/__Standard Values
SharedFields:
  - ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
    Hint: __Masters
    Value: |
      {F97EAA2D-5BE6-4403-A4A3-834C992BEDA5}
      {F21983D8-C426-4A3F-9307-C53FA3FB7DD1}
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
            Hint: __Created
            Value: 20230804T023318Z
          - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
            Hint: __Owner
            Value: |
              sitecore\Admin
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "8f1ba386-3ecd-4c03-a98b-73c13799d754"
          - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
            Hint: __Updated by
            Value: |
              sitecore\Admin
          - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
            Hint: __Updated
            Value: 20230804T023856Z
