---
ID: "1fe99d60-cda1-5dce-8d93-444540d11439"
Parent: "983b7245-0978-55b3-8ff7-48683349a741"
Template: "983b7245-0978-55b3-8ff7-48683349a741"
Path: "/sitecore/templates/Project/DemoSite/Styleguide/Styleguide-FieldUsage-File/__Standard Values"
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\JssImport
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "e8483175-10a9-4d5f-92e8-41cb2e962420"
