---
ID: "a63e8c37-82e7-4eb3-97b7-4edf268d377f"
Parent: "c5d60182-5b2d-44ae-89dd-1c60042a0ae6"
Template: "c5d60182-5b2d-44ae-89dd-1c60042a0ae6"
Path: /sitecore/templates/Feature/DemoSite/Navigation/Header/PrimaryNavigationMenuButton/__Standard Values
SharedFields:
  - ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
    Hint: __Masters
    Value: "{ABCBC0B5-CB96-48A3-8A06-806680EC9055}"
  - ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
    Hint: __Default workflow
    Value: "{33D3E219-6951-4F62-A015-183C3E1C4CF0}"
  - ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
    Hint: __Enable item fallback
    Value: 1
Languages:
  - Language: en
    Fields:
      - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
        Hint: __Display name
        Value:
    Versions:
      - Version: 1
        Fields:
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "b8a899e1-a7c7-4a16-8eb7-78814cb7d929"
