---
ID: "87c18813-66b3-4e60-8e6a-57f43671dd34"
Parent: "353741d2-6edc-4338-86fb-2914ddc0fe1e"
Template: "353741d2-6edc-4338-86fb-2914ddc0fe1e"
Path: /sitecore/templates/Feature/DemoSite/Listings/Link Listing/Link Item/__Standard Values
SharedFields:
  - ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
    Hint: __Default workflow
    Value:
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "ccbd0bcd-0b3e-4b78-bbfd-139d4192ae92"
          - ID: "bf8c78b3-ec6b-4c66-8b90-c16e18c8c830"
            Hint: linkText
            Value: $name
