---
ID: "ce12cd98-2aa2-443d-8b09-cb49aa485962"
Parent: "fdcf7fb4-436c-4e79-a94a-07bad3bc651d"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Foundation/DemoSite/Settings/ContentSettingsFolder
SharedFields:
  - ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
    Hint: __Icon
    Value: applications/32x32/folder_gear.png
  - ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
    Hint: __Base template
    Value: "{1930BBEB-7805-471A-A3BE-4858AC7CF696}"
  - ID: "f7d48a55-2158-4f02-9356-756654404f73"
    Hint: __Standard values
    Value: "{4A52B0CA-F3A5-40EA-8B49-D87EBC22D813}"
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\Admin
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "8a8220b1-c7de-4ad0-8910-6bb9b0a4efc1"
